version: "3.8"

x-app-variables: &app-variables
  - API_NAME=Music API
  - SENTRY_DSN=

  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_HOST=postgres
  - POSTGRES_DB=postgres


services:
  backend:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "
        alembic upgrade head &&
        cd app &&
        uvicorn main:app --reload --host 0.0.0.0 --port=8000
      "
    depends_on:
      - postgres
    environment: *app-variables

  postgres:
    image: postgres:12
    environment: *app-variables

volumes:
  postgres:
