version: "3.8"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      bash -c "cd app &&
      uvicorn main:app --reload --host 0.0.0.0 --port=8000"

  postgres:
    image: postgres:12

volumes:
  postgres:
